name: Check Script Permissions

on:
  push:
    branches:
      - main

jobs:
  check_permissions:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List file permissions
      run: ls -l $VM_ASSETS/select-xamarin-sdk-v2.sh
