name: Check Xamarin.Android Version

on:
  push:
    branches:
      - main

jobs:
  check_xamarin_android_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read Xamarin.Android Version
      run: |
        grep -oE 'Android\\[0-9]+\.[0-9]+' /usr/lib/mono/xbuild/Xamarin/Android/Xamarin.Android.CSharp.targets
