name: Build Xamarin.iOS app

on: [push]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=17

    - name: Set default Xcode 15
      run: |
        XCODE_ROOT=/Applications/Xcode_15.01.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT
   
    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: nuget restore App2/App2.sln

    - name: Build
      run: msbuild App2/App2/App2.iOS/App2.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
